# D - Regression with Keras

## Importing required libraries

In [3]:
import pandas as pd
import numpy as np

from tensorflow.keras import Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

## Download and Clean Dataset

<strong>The dataset is about the compressive strength of different samples of concrete based on the volumes of the different ingredients that were used to make them. Ingredients include:</strong>

1. Cement
2. Blast Furnace Slag
3. Fly Ash
4. Water
5. Superplasticizer
6. Coarse Aggregate
7. Fine Aggregate

In [6]:
# downloading and reading the data using pandas dataframe
concrete_data = pd.read_csv('https://cocl.us/concrete_data')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [7]:
concrete_data.shape

(1030, 9)

In [8]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [9]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

## Split data into predictors and target

In [11]:
concrete_data_columns = concrete_data.columns

# removing column 'Strength' and creating the predictors dataset
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] 

# creating target dataset with only 'Strength' column
target = concrete_data['Strength']

In [12]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [13]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

## Preparing data for regression

In [15]:
# Normalizing data 
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [16]:
n_cols = predictors_norm.shape[1]
n_cols

8

In [17]:
# Train an test split 
X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=42)

## Building a Neural Network

In [19]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_squared_error'])
    return model

## Train and Test the Network

In [21]:
# build the model
model = regression_model()

In [22]:
# fit the model
reg_model = model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
23/23 - 2s - 75ms/step - loss: 1560.0479 - mean_squared_error: 1560.0479
Epoch 2/100
23/23 - 0s - 2ms/step - loss: 1521.3763 - mean_squared_error: 1521.3763
Epoch 3/100
23/23 - 0s - 2ms/step - loss: 1466.2755 - mean_squared_error: 1466.2755
Epoch 4/100
23/23 - 0s - 2ms/step - loss: 1385.9586 - mean_squared_error: 1385.9586
Epoch 5/100
23/23 - 0s - 2ms/step - loss: 1269.1145 - mean_squared_error: 1269.1145
Epoch 6/100
23/23 - 0s - 2ms/step - loss: 1111.4509 - mean_squared_error: 1111.4509
Epoch 7/100
23/23 - 0s - 2ms/step - loss: 917.8876 - mean_squared_error: 917.8876
Epoch 8/100
23/23 - 0s - 2ms/step - loss: 709.3257 - mean_squared_error: 709.3257
Epoch 9/100
23/23 - 0s - 2ms/step - loss: 524.6980 - mean_squared_error: 524.6980
Epoch 10/100
23/23 - 0s - 2ms/step - loss: 388.7322 - mean_squared_error: 388.7322
Epoch 11/100
23/23 - 0s - 2ms/step - loss: 313.7529 - mean_squared_error: 313.7529
Epoch 12/100
23/23 - 0s - 2ms/step - loss: 271.0799 - mean_squared_error: 271.0799
Epoch 13/100
23/23 - 0s - 2ms/step - loss: 244.9234 - mean_squared_error: 244.9234
Epoch 14/100
23/23 - 0s - 2ms/step - loss: 226.8998 - mean_squared_error: 226.8998
Epoch 15/100
23/23 - 0s - 2ms/step - loss: 214.0674 - mean_squared_error: 214.0674
Epoch 16/100
23/23 - 0s - 2ms/step - loss: 203.6193 - mean_squared_error: 203.6193
Epoch 17/100
23/23 - 0s - 2ms/step - loss: 195.2814 - mean_squared_error: 195.2814
Epoch 18/100
23/23 - 0s - 2ms/step - loss: 188.7118 - mean_squared_error: 188.7118
Epoch 19/100
23/23 - 0s - 3ms/step - loss: 183.0408 - mean_squared_error: 183.0408
Epoch 20/100
23/23 - 0s - 2ms/step - loss: 178.2489 - mean_squared_error: 178.2489
Epoch 21/100
23/23 - 0s - 2ms/step - loss: 173.8087 - mean_squared_error: 173.8087
Epoch 22/100
23/23 - 0s - 2ms/step - loss: 169.9200 - mean_squared_error: 169.9200
Epoch 23/100
23/23 - 0s - 2ms/step - loss: 166.1410 - mean_squared_error: 166.1410
Epoch 24/100
23/23 - 0s - 2ms/step - loss: 162.8024 - mean_squared_error: 162.8024
Epoch 25/100
23/23 - 0s - 2ms/step - loss: 159.4764 - mean_squared_error: 159.4764
Epoch 26/100
23/23 - 0s - 2ms/step - loss: 156.6097 - mean_squared_error: 156.6097
Epoch 27/100
23/23 - 0s - 2ms/step - loss: 153.9404 - mean_squared_error: 153.9404
Epoch 28/100
23/23 - 0s - 2ms/step - loss: 151.5459 - mean_squared_error: 151.5459
Epoch 29/100
23/23 - 0s - 2ms/step - loss: 149.2908 - mean_squared_error: 149.2908
Epoch 30/100
23/23 - 0s - 2ms/step - loss: 147.0072 - mean_squared_error: 147.0072
Epoch 31/100
23/23 - 0s - 2ms/step - loss: 144.7446 - mean_squared_error: 144.7446
Epoch 32/100
23/23 - 0s - 2ms/step - loss: 142.5741 - mean_squared_error: 142.5741
Epoch 33/100
23/23 - 0s - 2ms/step - loss: 140.7449 - mean_squared_error: 140.7449
Epoch 34/100
23/23 - 0s - 2ms/step - loss: 138.5513 - mean_squared_error: 138.5513
Epoch 35/100
23/23 - 0s - 2ms/step - loss: 136.8456 - mean_squared_error: 136.8456
Epoch 36/100
23/23 - 0s - 2ms/step - loss: 135.1684 - mean_squared_error: 135.1684
Epoch 37/100
23/23 - 0s - 2ms/step - loss: 133.5752 - mean_squared_error: 133.5752
Epoch 38/100
23/23 - 0s - 2ms/step - loss: 131.5850 - mean_squared_error: 131.5850
Epoch 39/100
23/23 - 0s - 2ms/step - loss: 129.6578 - mean_squared_error: 129.6578
Epoch 40/100
23/23 - 0s - 2ms/step - loss: 127.8883 - mean_squared_error: 127.8883
Epoch 41/100
23/23 - 0s - 2ms/step - loss: 126.4235 - mean_squared_error: 126.4235
Epoch 42/100
23/23 - 0s - 2ms/step - loss: 124.6369 - mean_squared_error: 124.6369
Epoch 43/100
23/23 - 0s - 2ms/step - loss: 123.1094 - mean_squared_error: 123.1094
Epoch 44/100
23/23 - 0s - 2ms/step - loss: 121.0725 - mean_squared_error: 121.0725
Epoch 45/100
23/23 - 0s - 2ms/step - loss: 119.4654 - mean_squared_error: 119.4654
Epoch 46/100
23/23 - 0s - 2ms/step - loss: 118.1005 - mean_squared_error: 118.1005
Epoch 47/100
23/23 - 0s - 2ms/step - loss: 116.2586 - mean_squared_error: 116.2586
Epoch 48/100
23/23 - 0s - 2ms/step - loss: 114.8766 - mean_squared_error: 114.8766
Epoch 49/100
23/23 - 0s - 2ms/step - loss: 112.9884 - mean_squared_error: 112.9884
Epoch 50/100
23/23 - 0s - 2ms/step - loss: 111.4987 - mean_squared_error: 111.4987
Epoch 51/100
23/23 - 0s - 2ms/step - loss: 109.6721 - mean_squared_error: 109.6721
Epoch 52/100
23/23 - 0s - 2ms/step - loss: 108.0359 - mean_squared_error: 108.0359
Epoch 53/100
23/23 - 0s - 2ms/step - loss: 106.3202 - mean_squared_error: 106.3202
Epoch 54/100
23/23 - 0s - 2ms/step - loss: 104.6359 - mean_squared_error: 104.6359
Epoch 55/100
23/23 - 0s - 2ms/step - loss: 102.8992 - mean_squared_error: 102.8992
Epoch 56/100
23/23 - 0s - 2ms/step - loss: 101.0122 - mean_squared_error: 101.0122
Epoch 57/100
23/23 - 0s - 2ms/step - loss: 99.3289 - mean_squared_error: 99.3289
Epoch 58/100
23/23 - 0s - 2ms/step - loss: 97.5521 - mean_squared_error: 97.5521
Epoch 59/100
23/23 - 0s - 2ms/step - loss: 95.6064 - mean_squared_error: 95.6064
Epoch 60/100
23/23 - 0s - 2ms/step - loss: 93.9583 - mean_squared_error: 93.9583
Epoch 61/100
23/23 - 0s - 2ms/step - loss: 92.1115 - mean_squared_error: 92.1115
Epoch 62/100
23/23 - 0s - 2ms/step - loss: 90.1743 - mean_squared_error: 90.1743
Epoch 63/100
23/23 - 0s - 2ms/step - loss: 88.4734 - mean_squared_error: 88.4734
Epoch 64/100
23/23 - 0s - 2ms/step - loss: 86.4919 - mean_squared_error: 86.4919
Epoch 65/100
23/23 - 0s - 2ms/step - loss: 84.4628 - mean_squared_error: 84.4628
Epoch 66/100
23/23 - 0s - 2ms/step - loss: 82.4604 - mean_squared_error: 82.4604
Epoch 67/100
23/23 - 0s - 2ms/step - loss: 80.6376 - mean_squared_error: 80.6376
Epoch 68/100
23/23 - 0s - 2ms/step - loss: 78.8984 - mean_squared_error: 78.8984
Epoch 69/100
23/23 - 0s - 2ms/step - loss: 77.3689 - mean_squared_error: 77.3689
Epoch 70/100
23/23 - 0s - 2ms/step - loss: 75.7585 - mean_squared_error: 75.7585
Epoch 71/100
23/23 - 0s - 2ms/step - loss: 74.5276 - mean_squared_error: 74.5276
Epoch 72/100
23/23 - 0s - 2ms/step - loss: 72.6789 - mean_squared_error: 72.6789
Epoch 73/100
23/23 - 0s - 2ms/step - loss: 71.4153 - mean_squared_error: 71.4153
Epoch 74/100
23/23 - 0s - 2ms/step - loss: 70.0499 - mean_squared_error: 70.0499
Epoch 75/100
23/23 - 0s - 2ms/step - loss: 68.4520 - mean_squared_error: 68.4520
Epoch 76/100
23/23 - 0s - 4ms/step - loss: 67.3783 - mean_squared_error: 67.3783
Epoch 77/100
23/23 - 0s - 2ms/step - loss: 66.4100 - mean_squared_error: 66.4100
Epoch 78/100
23/23 - 0s - 2ms/step - loss: 65.2828 - mean_squared_error: 65.2828
Epoch 79/100
23/23 - 0s - 2ms/step - loss: 64.4484 - mean_squared_error: 64.4484
Epoch 80/100
23/23 - 0s - 2ms/step - loss: 63.5830 - mean_squared_error: 63.5830
Epoch 81/100
23/23 - 0s - 2ms/step - loss: 62.6278 - mean_squared_error: 62.6278
Epoch 82/100
23/23 - 0s - 2ms/step - loss: 61.6489 - mean_squared_error: 61.6489
Epoch 83/100
23/23 - 0s - 2ms/step - loss: 60.8284 - mean_squared_error: 60.8284
Epoch 84/100
23/23 - 0s - 2ms/step - loss: 60.4880 - mean_squared_error: 60.4880
Epoch 85/100
23/23 - 0s - 2ms/step - loss: 59.8139 - mean_squared_error: 59.8139
Epoch 86/100
23/23 - 0s - 2ms/step - loss: 59.1164 - mean_squared_error: 59.1164
Epoch 87/100
23/23 - 0s - 2ms/step - loss: 58.2513 - mean_squared_error: 58.2513
Epoch 88/100
23/23 - 0s - 2ms/step - loss: 57.7863 - mean_squared_error: 57.7863
Epoch 89/100
23/23 - 0s - 2ms/step - loss: 56.9684 - mean_squared_error: 56.9684
Epoch 90/100
23/23 - 0s - 2ms/step - loss: 56.4592 - mean_squared_error: 56.4592
Epoch 91/100
23/23 - 0s - 2ms/step - loss: 56.0484 - mean_squared_error: 56.0484
Epoch 92/100
23/23 - 0s - 2ms/step - loss: 54.9961 - mean_squared_error: 54.9961
Epoch 93/100
23/23 - 0s - 2ms/step - loss: 54.5817 - mean_squared_error: 54.5817
Epoch 94/100
23/23 - 0s - 2ms/step - loss: 54.0080 - mean_squared_error: 54.0080
Epoch 95/100
23/23 - 0s - 2ms/step - loss: 53.4389 - mean_squared_error: 53.4389
Epoch 96/100
23/23 - 0s - 2ms/step - loss: 53.6698 - mean_squared_error: 53.6698
Epoch 97/100
23/23 - 0s - 2ms/step - loss: 52.0160 - mean_squared_error: 52.0160
Epoch 98/100
23/23 - 0s - 2ms/step - loss: 51.4425 - mean_squared_error: 51.4425
Epoch 99/100
23/23 - 0s - 2ms/step - loss: 50.7421 - mean_squared_error: 50.7421
Epoch 100/100
23/23 - 0s - 2ms/step - loss: 50.2723 - mean_squared_error: 50.2723

In [23]:
mse_per_epoch = reg_model.history['mean_squared_error']

In [24]:
print(f"The mean of the MSE is: {np.mean(mse_per_epoch)}")

The mean of the MSE is: 208.80090732574462

In [25]:
print(f"The standard deviation of the MSE is: {np.std(mse_per_epoch)}")

The standard deviation of the MSE is: 323.3087530486774

## The mean of the mean squared errors has decreased compared to the previous task (C)